[package]
name = "effective"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
arena-link-tree = { path = "../arena-link-tree" }

[features]
default = ["extra-traits"]
extra-traits = []
